import { Geist, Geist_Mono, Montserrat, Raleway } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin', 'cyrillic'],
});

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin', 'cyrillic'],
});

const gilroy = Montserrat({
  variable: '--font-gilroy',
  subsets: ['latin', 'cyrillic'],
});

export const metadata = {
  title: 'Testovoe 4A Konsalting',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${gilroy.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
